### ISSUE TITLE
What is the format of the dataset?

### ISSUE THREAD

**Issue by ajesujoba** [henryzhao5852/DELFT#2]
Hi, thanks for the great work. I'm just trying to confirm if I can relate both the codes and the paper together. 
In the github page, little documentation was given with respect to the dataset format. Based on the codes I identified the format below, is it in anyway correct?
```
{'id': 123211,
'text': "question". 
'pos_et': {'et':et,'first_sent':firstsentnece,'evidence':[evidence]},
'neg_ets'. [{'et':et,'first_sent':firstsentnece,'evidence':[evidence]},{'et':et,'first_sent':firstsentnece,'evidence':[evidence]}....], 
'q_et': [{'text':text1,'entity':entity1}]??

}
```
where `test` in `q_et` is  same as node gloss??

Wrt the paper, can you explain what `pos_et` and `neg_ets` are? How are they gotten? 

Was the data formatted manually or there's a preprocessing pipeline?

**Comment by henryzhao5852** [comment]
Hi,

Yes, the ``text'' is the same as node gloss, sorry for the confusion. The positive entity is the answer, while the negatives are generated from the retrieval part.

**Comment by ajesujoba** [comment]
Hi @henryzhao5852, thank you for your response. 
Sorry I am asking more questions, but the retrieval part is not in the code on this GitHub page, right? 

For example, I have a dataset with Question and answer pair (Q,A) suppose I want to train a model or evaluate a model using DELFT, how do I correctly format the data using in the right way (including extracting the negatives)? Do you have a separate code/pipeline for that?

**Comment by henryzhao5852** [comment]
Yes, it's not included the repo (since it includes the Tagme part and is a bit complicated, therefore we directly provide the processed graph instead). Following the paper, you need to extract the question entities, find the related entities using Wiki graph, the entity matches the answer is the positive one, while the other entities are the negatives.
